### ISSUE TITLE
xxhash + zstd

### ISSUE THREAD

**Issue by doublex** [rescrv/Consus#4]
Maybe it would be worthwhile to add compression with "zstd" and to replace "crc32" with "xxhash"?

**Comment by rescrv** [comment]
crc32c was chosen because intel provides primitives that can be used with 1cycle/byte efficiency for larger values.  I'd rather stick with the well known in this case.

As for zstd, compression would be best implemented at the block level of the key-value store, like what LevelDB's snappy does.  It is possible to add snappy support with a line or two to the key-value store.

LevelDB is not a long term choice of backend, so I have not taken the time to pull out every trick in the book.

In any case, 99% of the costs of a transaction come from network latency and not the local CPU usage.
